### ISSUE TITLE
求运行方式说明

### ISSUE THREAD

**Issue by zsq19958629** [junxy/docker-clash#1]
已经在docker下边pull了镜像，但是该用什么参数进行运行呢？另外配置文件该如何生成？谢谢

**Comment by junxy** [comment]
修改 `config/config.yaml` （参考 https://github.com/Dreamacro/clash#toc4 ），然后运行 `docker-compose up -d` 

相关参考 
- https://github.com/Hackl0us/SS-Rule-Snippet/blob/master/LAZY_RULES/clash.yaml
- https://github.com/Dreamacro/clash/wiki/Run-clash-in-docker

**Comment by grayguest** [comment]
> 修改 `config/config.yaml` （参考 https://github.com/Dreamacro/clash#toc4 ），然后运行 `docker-compose up -d`
> 
> 相关参考
> 
> * https://github.com/Hackl0us/SS-Rule-Snippet/blob/master/LAZY_RULES/clash.yaml
> * https://github.com/Dreamacro/clash/wiki/Run-clash-in-docker

第二个参考链接木有了。。

**Comment by junxy** [comment]
> > 修改 `config/config.yaml` （参考 https://github.com/Dreamacro/clash#toc4 ），然后运行 `docker-compose up -d`
> > 相关参考
> > 
> > * https://github.com/Hackl0us/SS-Rule-Snippet/blob/master/LAZY_RULES/clash.yaml
> > * https://github.com/Dreamacro/clash/wiki/Run-clash-in-docker
> 
> 第二个参考链接木有了。。

移到了这里 https://github.com/Dreamacro/clash/wiki/Clash-as-a-daemon#docker
